chore: Update requirements.txt with new dependencies
amosproj/amos2024ss05-knowledge-graph-extractor pull request #89
Opened 2024-05-30 06:27 UTC by yashbhesaniya

## Description

* 

## Related Backlog Item

Issue: #

---

### Context

* 

---

## Checklist:
- [ ] I have documented my changes
- [ ] I have tested the changes and they work as expected
- [ ] I have assigned this PR to someone
- [ ] I have run `make format` to format my code

### Additional references

2024-06-01 14:12 UTC, nikolas-rauscher requested changes

2024-06-01 14:12 UTC, nikolas-rauscher commented on Project/backend/config/llm/gemini.py
> -    """
Did you intentionally remove the comments from the function, or was the branch not yet updated? @yashbhesaniya

2024-06-01 14:12 UTC, nikolas-rauscher commented on Project/backend/config/llm/llama3.py
> -    """
Same her?

2024-06-02 22:26 UTC, kristikotini requested changes
@yashbhesaniya  this PR was also reviewed by @nikolas-rauscher 
I also changed the base branch to develop and there are conflicts. 
I would suggest closing this PR and updating PR #91 (related to issue #55) since you also refactor the files there. 
If you still need a review for this please resolve the conflicts and comments from @nikolas-rauscher

2024-06-03 07:11 UTC, closed without merging